### ISSUE TITLE
Image file missing

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Toronto#1]
When running TD_dwellTime_osm_simulation.gaml the model cannot be run

Is it possible to add the file in the repo?

2 occurrences in 2 agents at cycle 0: File denoted by ../images/toronto-downtown-with-buildings-map.jpg not found.
in file<point, int> torontoMap <- file<point, int>('..\/images\/toronto-downtown-with-buildings-map.jpg') ;
/Users/Arno/Projects/Gama/MIT/GAMA_1.8/CSL_Toronto_GAMA/models/../images/toronto-downtown-with-buildings-map.jpg
/Users/Arno/Projects/Gama/MIT/GAMA_1.8/CSL_Toronto_GAMA/models/../images/toronto-downtown-with-buildings-map.jpg
in initializing attribute torontoMap
in agents Simulation 0, main0

**Comment by flybitsfarzin** [comment]
I just added images folder.

**Comment by agrignard** [comment]
Feel free to close the issue when you think it's done
