### ISSUE TITLE
Repository restructuration

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Toronto#2]
@flybitsfarzin would it be possible ot reorganize the repository structure so that all your includes and models are inside the CSL_Toronto_GAMA folder (which is the placeolder for the GAMA project)

Right now there is includes and models outside of this folder I don't know which one to use.

The idea is to put everything in the CSL_Toronto_GAMA so that it's easy to import from GAMA as it is a GAMA project (you can see there is a .project inside)

**Comment by flybitsfarzin** [comment]
Hi @agrignard, 

It's done.
